/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui2oyun;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author smhdg
 */
public class xoxgame extends javax.swing.JFrame {

    /**
     * Creates new form xoxgame
     */
    public xoxgame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblx = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btn4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btn5 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btn6 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lbl0 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        btn8 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        btn9 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        btnreset = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setForeground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new java.awt.GridLayout(3, 5, 2, 2));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn2.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn3.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new java.awt.GridLayout(1, 3, 2, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PLAYER   X  ");
        jPanel6.add(jLabel1);

        jPanel1.add(jPanel6);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        lblx.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        lblx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblx.setText("0");
        lblx.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(lblx);

        jPanel1.add(jPanel5);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn4.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn5.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn6.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new java.awt.GridLayout(1, 3, 2, 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PLAYER   O ");
        jPanel10.add(jLabel2);

        jPanel1.add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new java.awt.GridLayout(1, 3, 2, 2));

        lbl0.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        lbl0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl0.setText("0");
        lbl0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel11.add(lbl0);

        jPanel1.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn7.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn8.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel13);

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn9.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        btn9.setText(" ");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnreset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel15);

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnexit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnexit, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnexit, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel16);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        btn1.setText(null);
        btn2.setText(null);
        btn3.setText(null);
        btn4.setText(null);
        btn5.setText(null);
        btn6.setText(null);
        btn7.setText(null);
        btn8.setText(null);
        btn9.setText(null);
        b1=7;
        b2=7;
        b3=7;
        b4=7;
        b5=7;
        b6=7;
        b7=7;
        b8=7;
        b9=7;
        winning();
        startgame.equals("X");
        i=0;
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        int secenek=JOptionPane.showConfirmDialog(  
                null,
                "çıkmak istediğine emin misin?!" ,
                "",
                JOptionPane.YES_NO_OPTION);
        if (secenek==JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null,"oynamazsan oynama");
            System.exit(0);
        }else{
            JOptionPane.showMessageDialog(null,"tekrardan hellloo");
        }
        
    }//GEN-LAST:event_btnexitActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        btn1.setText(startgame); 
        if (startgame.equalsIgnoreCase("X")) {
            btn1.setForeground(Color.red);
            b1=1;
        }else{
            btn1.setForeground(Color.blue);
            b1=0;
        }
        chooseplayer();
        winning();
        i++;
// TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        btn2.setText(startgame); 
        if (startgame.equalsIgnoreCase("X")) {
            btn2.setForeground(Color.red);
            b2=1;
        }else{
            btn2.setForeground(Color.blue);
            b2=0;
        }
        chooseplayer();
        winning();
        i++;
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        btn3.setText(startgame); 
        if (startgame.equalsIgnoreCase("X")) {
            btn3.setForeground(Color.red);
            b3=1;
        }else{
            btn3.setForeground(Color.blue);
            b3=0;
        }
        chooseplayer();
        winning();
        i++;
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        btn4.setText(startgame); 
        if (startgame.equalsIgnoreCase("X")) {
            btn4.setForeground(Color.red);
            b4=1;
        }else{
            btn4.setForeground(Color.blue);
            b4=0;
        }
        chooseplayer();
        winning();
        i++;
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        btn5.setText(startgame); 
        if (startgame.equalsIgnoreCase("X")) {
            btn5.setForeground(Color.red);
            b5=1;
        }else{
            btn5.setForeground(Color.blue);
            b5=0;
        }
        chooseplayer();
        winning();
        i++;
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        btn6.setText(startgame); 
        if (startgame.equalsIgnoreCase("X")) {
            btn6.setForeground(Color.red);
            b6=1;
        }else{
            btn6.setForeground(Color.blue);
            b6=0;
        }
        chooseplayer();
        winning();
        i++;
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        btn7.setText(startgame); 
        if (startgame.equalsIgnoreCase("X")) {
            btn7.setForeground(Color.red);
            b7=1;
        }else{
            btn7.setForeground(Color.blue);
            b7=0;    
        }
        chooseplayer();
        winning();
        i++;
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        btn8.setText(startgame); 
        if (startgame.equalsIgnoreCase("X")) {
            btn8.setForeground(Color.red);
            b8=1;
        }else{
            btn8.setForeground(Color.blue);
            b8=0;
        }
        chooseplayer();
        winning();
        i++;
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        btn9.setText(startgame); 
        if (startgame.equalsIgnoreCase("X")) {
            btn9.setForeground(Color.red);
            b9=1;
        }else{
            btn9.setForeground(Color.blue);
            b9=0;
        }
        chooseplayer();
        winning();
        i++;
    }//GEN-LAST:event_btn9ActionPerformed
    
    private String startgame="X";
    private int b1=7;
    private int b2=7;
    private int b3=7;
    private int b4=7;
    private int b5=7;
    private int b6=7;
    private int b7=7;
    private int b8=7;
    private int b9=7;
    private int i=0;
    
    //metodlar:
    
    private void winning(){
        //for x ;
        if (b1==1 && b2==1  && b3==1) {
            JOptionPane.showMessageDialog(null, "player X wins! ","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lblx.getText());
            sayac++;
            lblx.setText(String.valueOf(sayac));
        }
        if (b4==1 && b5==1  && b6==1) {
            JOptionPane.showMessageDialog(null, "player X wins! ","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lblx.getText());
            sayac++;
            lblx.setText(String.valueOf(sayac));
        }
        if (b7==1 && b8==1  && b9==1) {
            JOptionPane.showMessageDialog(null, "player X wins! ","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lblx.getText());
            sayac++;
            lblx.setText(String.valueOf(sayac));
        }
        if (b1==1 && b4==1  && b7==1) {
            JOptionPane.showMessageDialog(null, "player X wins! ","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lblx.getText());
            sayac++;
            lblx.setText(String.valueOf(sayac));
        }
        if (b2==1 && b5==1  && b8==1) {
            JOptionPane.showMessageDialog(null, "player X wins! ","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lblx.getText());
            sayac++;
            lblx.setText(String.valueOf(sayac));
        }
        if (b3==1 && b6==1  && b9==1) {
            JOptionPane.showMessageDialog(null, "player X wins! ","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lblx.getText());
            sayac++;
            lblx.setText(String.valueOf(sayac));
        }
        if (b1==1 && b5==1  && b9==1) {
            JOptionPane.showMessageDialog(null, "player X wins! ","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lblx.getText());
            sayac++;
            lblx.setText(String.valueOf(sayac));
        }
        if (b3==1 && b5==1  && b7==1) {
            JOptionPane.showMessageDialog(null, "player X wins! ","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lblx.getText());
            sayac++;
            lblx.setText(String.valueOf(sayac));
        }
        //for 0;
        if (b1==0 && b2==0 && b3==0) {
            JOptionPane.showMessageDialog(null,"Player O vins!","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lbl0.getText());
            sayac++;
            lbl0.setText(String.valueOf(sayac));
        }
        if (b4==0 && b5==0 && b6==0) {
            JOptionPane.showMessageDialog(null,"Player O vins!","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lbl0.getText());
            sayac++;
            lbl0.setText(String.valueOf(sayac));
        }
        if (b7==0 && b8==0 && b9==0) {
            JOptionPane.showMessageDialog(null,"Player O vins!","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lbl0.getText());
            sayac++;
            lbl0.setText(String.valueOf(sayac));
        }
        if (b1==0 && b4==0 && b7==0) {
            JOptionPane.showMessageDialog(null,"Player O vins!","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lbl0.getText());
            sayac++;
            lbl0.setText(String.valueOf(sayac));
        }
        if (b1==0 && b5==0 && b9==0) {
            JOptionPane.showMessageDialog(null,"Player O vins!","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lbl0.getText());
            sayac++;
            lbl0.setText(String.valueOf(sayac));
        }
        if (b8==0 && b2==0 && b5==0) {
            JOptionPane.showMessageDialog(null,"Player O vins!","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lbl0.getText());
            sayac++;
            lbl0.setText(String.valueOf(sayac));
        }
        if (b3==0 && b6==0 && b9==0) {
            JOptionPane.showMessageDialog(null,"Player O vins!","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lbl0.getText());
            sayac++;
            lbl0.setText(String.valueOf(sayac));
        }
        if (b7==0 && b5==0 && b3==0) {
            JOptionPane.showMessageDialog(null,"Player O vins!","",JOptionPane.INFORMATION_MESSAGE);
            int sayac=Integer.parseInt(lbl0.getText());
            sayac++;
            lbl0.setText(String.valueOf(sayac));
        }
        if (i==9) {
            JOptionPane.showMessageDialog(null,"THERE IS NO WINNER! PLEASE RESET AND PLAY AGAIN");
        }
        
        
    }
    private void chooseplayer(){
        if (startgame.equalsIgnoreCase("X")) {
            startgame="O";
        }
        else{
            startgame="X";
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xoxgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xoxgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xoxgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xoxgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new xoxgame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl0;
    private javax.swing.JLabel lblx;
    // End of variables declaration//GEN-END:variables

    
}
